namespace TheSushiRoles
{
    public enum MurderAttemptResult 
    {
        PerformKill,
        SuppressKill,
        BlankKill,
        DelayViperKill,
        MirrorKill,
    }
    public enum CustomOptionType
    {
        General,
        Impostor,
        Neutral,
        Crewmate,
        Modifier,
        Ability
    }
    public enum AbilityId
    {
        Coward,
        Paranoid
    }
    public enum ModifierId
    {
        Lover,
        Disperser,
        Bait,
        Lazy,
        Sleuth,
        Tiebreaker,
        Giant,
        Sidekick,
        Blind,
        Mini,
        Vip,
        Drunk,
        Chameleon,
        Lucky
    }
    public enum RoleAlignment
    {
        CrewPower,
        CrewSupport,
        CrewSpecial,
        CrewProtect,
        CrewInvest,
        NeutralBenign,
        NeutralEvil,
        NeutralKilling,
        ImpPower,
        ImpSpecial,
        ImpConcealing,
        ImpSupport,
        None
    }
    public enum RoleId 
    {
        Jester,
        Mayor,
        Gatekeeper,
        Grenadier,
        Landlord,
        Oracle,
        Miner,
        Engineer,
        Sheriff,
        Juggernaut,
        Glitch,
        Lighter,
        Agent,
        Hitman,
        Veteran,
        Detective,
        Predator,
        Chronos,
        Medic,
        Romantic,
        Swapper,
        Mystic,
        Morphling,
        Camouflager,
        Hacker,
        Crusader,
        Tracker,
        Viper,
        Jackal,
        Eraser,
        Spy,
        VengefulRomantic,
        Trickster,
        Janitor,
        Monarch,
        Blackmailer,
        Warlock,
        Werewolf,
        Vigilante,
        Arsonist,
        BountyHunter,
        Wraith,
        Vulture,
        Medium,
        Pestilence,
        Plaguebearer,
        Trapper,
        Undertaker,
        Lawyer,
        Prosecutor,
        Survivor,
        Witch,
        Assassin,
        Yoyo,
        Amnesiac,
        Crewmate,
        Impostor,
    }

    public enum CustomRPC
    {
        // Main Controls

        ResetVaribles = 100,
        ShareOptions,
        ForceEnd,
        WorkaroundSetRoles,
        SetRole,
        SetModifier,
        SetAbility,
        VersionHandshake,
        UseUncheckedVent,
        SetPostRoles,
        UncheckedMurderPlayer,
        WerewolfMaul,
        UncheckedCmdReportDeadBody,
        SetUnteleportable,
        RemoveAllBodies,
        UncheckedExilePlayer,
        DynamicMapOption,
        SetGameStarting,
        StopStart,

        // Role functionality

        EngineerFixLights = 120,
        EngineerFixSubmergedOxygen,
        EngineerUsedRepair,
        CleanBody,
        CreateHook,
        UpdateHook,
        MedicSetShielded,
        StopFortifiedInteraction,
        TurnPestilence,
        ShieldedMurderAttempt,
        GlitchMimic,
        SetJesterWinner,
        HitmanMorph,
        HitmanDragBody,
        HitmanDropBody,
        PestilenceKill,
        DropBody,
        DragBody,
        Disperse,
        VeteranAlert,
        AmnesiacRemember,
        Fortify,
        Confess,
        VeteranAlertKill,
        ChronosRewindTime,
        FortifiedMurderAttempt,
        DraftModePickOrder,
        DraftModePick,
        SwapperSwap,
        MorphlingMorph,
        CamouflagerCamouflage,
        GrenadierFlash,
        TrackerUsedTracker,
        ViperSetPoisoned,
        GlitchUsedHacks,
        JackalCreatesSidekick,
        ErasePlayerRoles,
        SetFutureErased,
        SetFutureShielded,
        SetFutureSpelled,
        PlaceAssassinTrace,
        PlacePortal,
        PlaceMine,
        UsePortal,
        PlaceJackInTheBox,
        LightsOut,
        PlaceCamera,
        SealVent,
        ArsonistWin,
        Guesserhoot,
        RomanticSetBeloved,
        AgentTurnIntoHitman,
        LawyerSetTarget,
        LawyerChangeRole,
        ProsecutorSetTarget,
        LandlordTeleport,
        MonarchKnight,
        RomanticChangeRole,
        ProsecutorChangeRole,
        SetBlanked,
        SetFirstKill,
        Drunk,
        SetTiebreak,
        SetInvisible,
        SetVanish,
        BlackmailerBlackmail,
        RemoveBlackmail,
        SetTrap,
        SetBlindTrap,
        TriggerTrap,
        TriggerBlindTrap,
        MayorSetVoteTwice,
        YoyoMarkLocation,
        YoyoBlink,
        BreakArmor,
        SetGuesser,

        // Other functionality
        ShareTimer,
        ShareGhostInfo,
    }
    public enum Faction
    {
        Crewmates,
        Neutrals,
        Impostors,
        Other
    }
    public enum GhostInfoTypes 
    {
        HackNoticed,
        HackOver,
        ArsonistDouse,
        BountyTarget,
        AssassinMarked,
        OracleInfo,
        PlaguebearerInfect,
        WarlockTarget,
        MysticInfo,
        MediumInfo,
        BlankUsed,
        DetectiveOrMedicInfo,
        ViperTimer,
        DeathReasonAndKiller,
    }
    enum CustomGameOverReason 
    {
        LoversWin = 10,
        TeamJackalWin = 11,
        MiniLose = 12,
        JesterWin = 13,
        ArsonistWin = 14,
        VultureWin = 15,
        ProsecutorWin = 16,
        GlitchWin = 17,
        WerewolfWin = 18,
        PredatorWin = 19,
        VRomanticWin = 20,
        JuggernautWin = 21,
        PestilenceWin = 22,
        PlaguebearerWin = 23,
        AgentWin = 24,
        HitmanWin = 25,
    }

    enum WinCondition 
    {
        Default,
        LoversTeamWin,
        LoversSoloWin,
        JesterWin,
        JackalWin,
        MiniLose,
        ArsonistWin,
        VultureWin,
        AdditionalLawyerBonusWin,
        AdditionalRomanticBonusWin,
        AdditionalAliveSurvivorWin,
        AdditionalBelovedBonusWin,
        AdditionalLoversPartnerWin,
        ProsecutorWin,
        GlitchWin,
        WerewolfWin,
        PredatorWin,
        VRomanticWin,
        JuggernautWin,
        PestilenceWin,
        PlaguebearerWin,
        AgentWin,
        HitmanWin,
    }
}